# Generated by Django 3.0 on 2019-12-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default='Medical'),
        ),
    ]
