# Generated by Django 3.0 on 2019-12-11 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191211_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 11, 8, 39, 30, 934274, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='dateProcessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
